import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="flex flex-wrap justify-between mx-4">
					<Link href="/">Home</Link>
					<Link href="/employment">Employment</Link>
					<Link href="/education">Education</Link>
					<Link href="/contact">Contact</Link>
					<Link href="/references">References</Link>
					<Link href="/testimonials">Testimonials</Link>
					<Link href="/resume">Resume</Link>
					<Link href="/links">Links</Link>
				</nav>
				{children}
			</body>
		</html>
	)
}
